import random
comp=random.randrange(0,20)
user=None
while user==None:
        user=input("Guess the Number generated by the computer between 0 to 20: ")
        user=int(user)
        if user>20:
                print("Please choose between 0 to 20.")
        
        if user==comp:
                print("You Guessed it Right. The Number is {}".format(comp))
                comp=random.randrange(0,20)
        if user<comp:
                print(str(user)+" is lower than the number")
        elif user>comp:
                print(str(user)+" is greater than the number")
        user=None

        
 
